#!/usr/bin/env bash
# Autogenerated script, compiled from the Bish language.
# Bish version 0.1
# Please see https://github.com/tdenniston/bish for more information about Bish.

function bish_exit_code () {
    thecommand="$1";
    $thecommand;
}

function bish_command_exists () {
    thecommand="$1";
    returned=$(bish_exit_code "command -v $thecommand >/dev/null 2>&1");
    if [[ $returned -eq 0 ]]; then
        echo 0; exit;
    else
        echo 1; exit;
    fi;
}

function bish_install_package () {
    thepackage="$1";
    if [[ $(bish_command_exists $thepackage) -ne 1 ]]; then
        "pacman -S $thepackage --noconfirm";
        bish_println "Finished configuring Raspberry Pi";
    else
        bish_println "wpa_supplicant already installed";
    fi;
}

function bish_main () {
    if [[ $(du -k /etc/ssh/ssh_host_key | cut -f1) -eq 0 ]]; then
        pacman -Rsn openssh;
        rm -rf /etc/ssh;
        pacman -S openssh;
        systemctl start sshd;
        systemctl enable ssh;
    fi;
    bish_install_package "wpa_supplicant";
}

function bish_println () {
    echo -e "$1";
}

bish_main;
